<!DOCTYPE html>
<html>
<head>
    <title> - HNG OJET</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="bootstrap-theme.css">
    <link rel="stylesheet" type="text/css" href="styles.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="index.html">HNG OJET</a>
        </div>
    </div>
</nav><div class="container-fluid">
    <div class="row">
                <div class="col-sm-4 col-md-3 sidebar">
	<div class="panel-group" role="tablist">
		<div class="panel panel-default">
					
																									

			<div class="panel-heading" role="tab" id="collapseListGroupHeading1">
				<h4 class="panel-title"> <a href="#collapseListGroup1" class="collapsed" role="button" data-toggle="collapse" aria-expanded="false" aria-controls="collapseListGroup1">Auth</a> </h4>
			</div>
			<div class="panel-collapse collapse " role="tabpanel" id="collapseListGroup1" aria-labelledby="collapseListGroupHeading1" aria-expanded="false" style="height: 0px;">
				<ul class="list-group">
					

															<li style="word-wrap: break-word;" class="list-group-item ">
						<a href="requests/post_Register.html">POST - Register</a>
					</li>
															<li style="word-wrap: break-word;" class="list-group-item ">
						<a href="requests/post_Login.html">POST - Login</a>
					</li>
									</ul> 
			</div>
					
																																																										

			<div class="panel-heading" role="tab" id="collapseListGroupHeading2">
				<h4 class="panel-title"> <a href="#collapseListGroup2" class="collapsed" role="button" data-toggle="collapse" aria-expanded="false" aria-controls="collapseListGroup2">Category</a> </h4>
			</div>
			<div class="panel-collapse collapse " role="tabpanel" id="collapseListGroup2" aria-labelledby="collapseListGroupHeading2" aria-expanded="false" style="height: 0px;">
				<ul class="list-group">
					

															<li style="word-wrap: break-word;" class="list-group-item ">
						<a href="requests/get_Get_list_of_Categories.html">GET - Get list of Categories</a>
					</li>
															<li style="word-wrap: break-word;" class="list-group-item ">
						<a href="requests/post_Create_a_new_Category.html">POST - Create a new Category</a>
					</li>
															<li style="word-wrap: break-word;" class="list-group-item ">
						<a href="requests/get_Get_Category_by_ID.html">GET - Get Category by ID</a>
					</li>
															<li style="word-wrap: break-word;" class="list-group-item ">
						<a href="requests/put_Update_Category.html">PUT - Update Category</a>
					</li>
															<li style="word-wrap: break-word;" class="list-group-item ">
						<a href="requests/delete_Delete_a_Category.html">DELETE - Delete a Category</a>
					</li>
									</ul> 
			</div>
					
														

			<div class="panel-heading" role="tab" id="collapseListGroupHeading3">
				<h4 class="panel-title"> <a href="#collapseListGroup3" class="collapsed" role="button" data-toggle="collapse" aria-expanded="false" aria-controls="collapseListGroup3">Post</a> </h4>
			</div>
			<div class="panel-collapse collapse " role="tabpanel" id="collapseListGroup3" aria-labelledby="collapseListGroupHeading3" aria-expanded="false" style="height: 0px;">
				<ul class="list-group">
					

															<li style="word-wrap: break-word;" class="list-group-item ">
						<a href="requests/get_Get_all_Posts.html">GET - Get all Posts</a>
					</li>
									</ul> 
			</div>
				</div> 
	</div>
</div>
        <div class="col-sm-8 col-sm-offset-4 col-md-9 col-md-offset-3 main">
            <h1> HNG OJET API Documentation </h1>

            <br>
            <footer>
                API Documentation generated by <a href="https://github.com/JakeWorrell/docodile">Docodile</a> on 10/06/2019 at 08:01:51
            </footer>
        </div>
    </div>

</div>

    <script src="bootstrap/js/bootstrap.min.js"></script>
</body>
</html>
